[platformio]
include_dir = inc

[env]
platform = platformio/espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
build_flags =
    -D USER_SETUP_LOADED=1
    -include inc/tft_espi_setup.h
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:a]
build_flags =
    ${env.build_flags}
    -DBOARD_ROLE_A
upload_port = /dev/cu.usbmodem1101

[env:b]
build_flags =
    ${env.build_flags}
    -DBOARD_ROLE_B
upload_port = /dev/cu.usbmodem4